package code

var zhCNText = map[int]string{
	ServerError:        "内部服务器错误",
	TooManyRequests:    "请求过多",
	ParamBindError:     "参数信息错误",
	AuthorizationError: "签名信息错误",
	UrlSignError:       "参数签名错误",
	CacheSetError:      "设置缓存失败",
	CacheGetError:      "获取缓存失败",
	CacheDelError:      "删除缓存失败",
	CacheNotExist:      "缓存不存在",
	ResubmitError:      "请勿重复提交",
	HashIdsEncodeError: "HashID 加密失败",
	HashIdsDecodeError: "HashID 解密失败",
	RBACError:          "暂无访问权限",
	RedisConnectError:  "Redis 连接失败",
	MySQLConnectError:  "MySQL 连接失败",
	WriteConfigError:   "写入配置文件失败",
	SendEmailError:     "发送邮件失败",
	MySQLExecError:     "SQL 执行失败",
	GoVersionError:     "Go 版本不满足要求",
	SocketConnectError: "Socket 未连接",
	SocketSendError:    "Socket 消息发送失败",

	AuthorizedCreateError:    "创建调用方失败",
	AuthorizedListError:      "获取调用方列表失败",
	AuthorizedDeleteError:    "删除调用方失败",
	AuthorizedUpdateError:    "更新调用方失败",
	AuthorizedDetailError:    "获取调用方详情失败",
	AuthorizedCreateAPIError: "创建调用方 API 地址失败",
	AuthorizedListAPIError:   "获取调用方 API 地址列表失败",
	AuthorizedDeleteAPIError: "删除调用方 API 地址失败",

	AdminCreateError:             "创建管理员失败",
	AdminListError:               "获取管理员列表失败",
	AdminDeleteError:             "删除管理员失败",
	AdminUpdateError:             "更新管理员失败",
	AdminResetPasswordError:      "重置密码失败",
	AdminLoginError:              "登录失败",
	AdminLogOutError:             "退出失败",
	AdminModifyPasswordError:     "修改密码失败",
	AdminModifyPersonalInfoError: "修改个人信息失败",
	AdminMenuListError:           "获取管理员菜单授权列表失败",
	AdminMenuCreateError:         "管理员菜单授权失败",
	AdminOfflineError:            "下线管理员失败",
	AdminDetailError:             "获取个人信息失败",

	MenuCreateError:       "创建菜单失败",
	MenuUpdateError:       "更新菜单失败",
	MenuDeleteError:       "删除菜单失败",
	MenuListError:         "获取菜单列表失败",
	MenuDetailError:       "获取菜单详情失败",
	MenuCreateActionError: "创建菜单栏功能权限失败",
	MenuListActionError:   "获取菜单栏功能权限列表失败",
	MenuDeleteActionError: "删除菜单栏功能权限失败",

	CronCreateError:  "创建后台任务失败",
	CronUpdateError:  "更新后台任务失败",
	CronListError:    "获取定时任务列表失败",
	CronDetailError:  "获取定时任务详情失败",
	CronExecuteError: "手动执行定时任务失败",

	AgentCreateError:           "创建代理失败",
	AgentListError:             "获取代理列表失败",
	AgentDeleteError:           "删除代理失败",
	AgentUpdateError:           "更新代理失败",
	AgentDetailError:           "获取代理详情失败",
	AgentNameExistError:        "代理名称已存在",
	OperationAccountExistError: "运营账户已存在",
	PayinShareError:            "代收分成不能大于100%",
	PayoutShareError:           "代付分成不能大于100%",
	ExchangeRateError:          "汇率不能小于等于0",
	AgentStatusError:           "状态只能为0或1",
	AgentIdError:               "代理ID错误",

	MerchantCreateError:       "创建商户失败",
	MerchantUpdateError:       "更新商户失败",
	MerchantListError:         "获取商户列表失败",
	MerchantDeleteError:       "删除商户失败",
	MerchantDetailError:       "获取商户详情失败",
	MerchantNameExistError:    "商户名称已存在",
	MerchantIdError:           "商户ID错误",
	MerchantStatusError:       "商户状态只能为0或1",
	MerchantTypeError:         "商户类型只能为0或1",
	MerchantSecretError:       "商户密钥只能为32位字符串",
	MerchantPayinShareError:   "商户代收分成不能大于100%",
	MerchantPayoutShareError:  "商户代付分成不能大于100%",
	MerchantExchangeRateError: "商户汇率不能小于等于0",

	AgentSettlementCreateError: "创建代理结算失败",
	AgentSettlementUpdateError: "更新代理结算失败",
	AgentSettlementListError:   "获取代理结算列表失败",
	AgentSettlementDeleteError: "删除代理结算失败",
	AgentSettlementDetailError: "获取代理结算详情失败",

	CountryUpdateError:    "更新国家失败",
	CountryCreateError:    "创建国家失败",
	CountryListError:      "获取国家列表失败",
	CountryDetailError:    "获取国家详情失败",
	CountryDeleteError:    "删除国家失败",
	CountryIdError:        "国家ID错误",
	CountryNameExistError: "国家名称已存在",

	MerchantChannelCreateError: "创建商户渠道失败",
	MerchantChannelUpdateError: "更新商户渠道失败",
	MerchantChannelDetailError: "获取商户渠道详情失败",

	WhiteListCreateError:  "创建白名单失败",
	WhiteListListError:    "获取白名单列表失败",
	WhiteListDeleteError:  "删除白名单失败",
	WhiteListIpExistError: "IP地址已存在",

	ChannelCreateError:    "创建通道失败",
	ChannelUpdateError:    "更新通道失败",
	ChannelListError:      "获取通道列表失败",
	ChannelDeleteError:    "删除通道失败",
	ChannelDetailError:    "获取通道详情失败",
	ChannelIdError:        "通道ID错误",
	ChannelNameExistError: "通道名称已存在",
	ChannelStatusError:    "通道状态只能为0或1",
	ChannelTypeError:      "通道类型只能为0或1",

	PayinDailyStatsListError:    "获取代收统计列表失败",
	PayinDailyStatsExportError:  "导出代收统计失败",
	PayoutDailyStatsListError:   "获取代付统计列表失败",
	PayoutDailyStatsExportError: "导出代付统计失败",
	PayinDailyStatsDetailError:  "获取代收统计详情失败",
	PayoutDailyStatsDetailError: "获取代付统计详情失败",
	PayinDailyStatsCreateError:  "创建代收统计失败",
	PayoutDailyStatsCreateError: "创建代付统计失败",
	PayinDailyStatsUpdateError:  "更新代收统计失败",
	PayoutDailyStatsUpdateError: "更新代付统计失败",
	PayinDailyStatsDeleteError:  "删除代收统计失败",
	PayoutDailyStatsDeleteError: "删除代付统计失败",
	PayinDailyStatsIdError:      "代收统计ID错误",
	PayoutDailyStatsIdError:     "代付统计ID错误",

	DailySummaryReportError: "日汇总数据统计失败",

	WithdrawalCreateError:       "创建提现记录失败",
	WithdrawalUpdateError:       "更新提现记录失败",
	WithdrawalListError:         "获取提现记录列表失败",
	WithdrawalDeleteError:       "删除提现记录失败",
	WithdrawalDetailError:       "获取提现记录详情失败",
	WithdrawalIdError:           "提现记录ID错误",
	WithdrawalStatisticsError:   "提现统计失败",
	WithdrawalUpdateStatusError: "更新提现状态失败",
	WithdrawalExportError:       "导出提现记录失败",
	WithdrawalReviewError:       "审核提现申请失败",

	// 结算相关错误信息
	SettlementInvalidParams:  "结算参数错误",
	SettlementOrderNotFound:  "结算订单不存在",
	SettlementStatusInvalid:  "订单状态不允许结算",
	SettlementAlreadySettled: "订单已结算",
	SettlementDBOperation:    "结算数据库操作失败",
}
